version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - echo "Instalando dependencias..."
      - cp ../Procfile blacklist_service/              # ðŸ” Copiar el Procfile al root del artefacto
      - cp ../Dockerrun.aws.json blacklist_service/
      - cd blacklist_service
      - pip install --upgrade pip
      - pip install -r requirements.txt --verbose

  build:
    commands:
      - echo "âœ… Build completado. Preparando artefactos para despliegue..."
      - pytest tests/ --maxfail=1 --disable-warnings --tb=short > result.log || true

artifacts:
  base-directory: 'blacklist_service'
  files:
    - '**/*'
    - ../result.log
