version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Instalando dependencias...
      - pip install -r blacklist_service/requirements.txt
      - pip install pytest faker
      - echo Autenticando en Docker Hub...
      - export DOCKER_USERNAME=$(aws secretsmanager get-secret-value --secret-id dockerhub/credentials --query SecretString --output text | jq -r .username)
      - export DOCKER_PASSWORD=$(aws secretsmanager get-secret-value --secret-id dockerhub/credentials --query SecretString --output text | jq -r .password)
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  pre_build:
    commands:
      - echo Ejecutando pruebas unitarias...
      - export PYTHONPATH=$PYTHONPATH:$(pwd)/blacklist_service
      - pytest blacklist_service/tests/

  build:
    commands:
      - echo Construcción completada exitosamente.
      - echo Construyendo imagen Docker...
      - docker build -t mi-microservicio -f blacklist_service/Dockerfile blacklist_service

  post_build:
    commands:
      - echo Fase post_build finalizada.
      - echo Iniciando login en Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 416825837619.dkr.ecr.us-east-1.amazonaws.com
      - export REPOSITORY_URI=416825837619.dkr.ecr.us-east-1.amazonaws.com/blacklist-service
      - export IMAGE_TAG=latest
      - docker tag mi-microservicio:latest $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "[{\"name\":\"blacklist\",\"imageUri\":\"$REPOSITORY_URI:$IMAGE_TAG\"}]" > imagedefinitions.json

artifacts:
  files:
    - '**/appspec.json'
    - '**/taskdef.json'
    - '**/imagedefinitions.json'