version: '3.8'

services:
  blacklist_service:
    build: ./blacklist_service
    ports:
      - "5000:5000"
    volumes:
      - ./blacklist_service/newrelic.ini:/app/newrelic.ini
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/blacklist_db
      - JWT_SECRET_KEY=supersecret
      - NEW_RELIC_CONFIG_FILE=/app/newrelic.ini
    depends_on:
      - db
    
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: blacklist_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"